---
api-version: 1.18
author: VapoR
commands:
  tpll:
    description: "Teleports player to latitude longitude coordinates."
    permission: vt.tpll
    usage: /tpll
  distortion:
    description: "Returns amount of distortion due to the projection at the player's location."
    permission: vt.terra.distortion
    usage: /distortion
  where:
    aliases:
      - ll
      - whereami
    description: "Returns your location in relation to the real world."
    permission: vt.terra.where
    usage: /where
  vt-reload:
    description: "Reloads plugin config."
    permission: vt.reload
    usage: /vt-reload
permissions:
  vt.*:
    description: "Wild card"
    children:
      vt.reload: true
      vt.tpll: true
      vt.terra: true
      vt.terra.distortion: true
      vt.terra.where: true
  vt.reload:
    description: "Allows usage of /vt-reload"
  vt.tpll:
    description: "Allows usage of /tpll"
  vt.terra.*:
    description: "Allows usage of all terra commands"
    children:
      vt.terra.distortion: true
      vt.terra.where: true
  vt.terra.distortion:
    description: "Allows usage of /distortion"
  vt.terra.where:
    description: "Allows usage of /where"
main: "com.github.vaporrrr.vanillaterra.VanillaTerra"
name: "VanillaTerra"
version: 1.0.7
